


baseURL = 'https://lichturm.de/'
title = 'Lichturm'
theme = "poison"
paginate = 10
pluralizelisttitles = false



# BEGIN MULTILANGUAGE SETUP
languageCode = 'de-DE'
defaultContentLanguage = 'en'
[languages]
  [languages.de]
    contentDir = 'content/de'
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 1
    [languages.de.params]
      description = 'Welch schreckliche Nacht des Lesens mächtig zu sein!'
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-GB'
    languageName = 'English'
    weight = 2
    [languages.en.params]
      description = 'What a horrible night to be literate!'
# END MULTILANGUAGE SETUP



[params]
    # BEGIN My stuff
    #disableJS = true
    front_page_content = ["posts", "about"]
    # END My stuff
    brand = "Lichturm"
    # this refers to the images directory contained within static
    brand_image = "/images/lichturm.png"
    # og_image = ""                             # path to social icon - front matter: image takes precedent, then og_image, then brand_url
    # publisher_icon = ""                       # path to publisher icon - defaults to favicon, used in schema
    favicon = "/images/lichturm_favicon.png"    # path to favicon
    #description = 'Dare you enter my magical realm?'
    dark_mode = true

    # mostly copy pasted from poison docs ...
    menu = [
        # Dict keys:
            # Name:         The name to display on the menu.
            # URL:          The directory relative to the content directory.
            # HasChildren:  If the directory's files should be listed.  Default is true.
            # Limit:        If the files should be listed, how many should be shown.

        # SINGLE PAGE
        # Note that you must put your markdown file 
        # inside of a directory with the same name.

        # ... /content/about/about.md
        {Name = "About", URL = "/about/", HasChildren = false},
        
        # ... /content/foo/_index.md
        # {Name = "Foo", URL = "/foo/", HasChildren = false},

        # LIST
        # This example has a subheading of "Recent" and will display up to 5 items.
        # ... /content/posts/introducing-poison.md
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},

        # Example of a list without a subheading or limit.
        #{Name = "Projects", URL = "/projects/"},
    ]

    github_url = "https://github.com"
    linkedin_url = "https://linkedin.com"
    #x_url = "https://x.com"
    #discord_url = "https://discord.com"
    #youtube_url = "https://youtube.com"
    email_url = "mailto://lichturm@posteo.de"


    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "posts"

    # sidebar
    sidebar_bg_color = "#202020"            # default is #202020
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_h1_color = "#FFF"               # default is #FFF
    sidebar_a_color = "#FFF"                # default is #FFF
    sidebar_socials_color = "#FFF"          # default is #FFF
    moon_sun_color = "#FFF"                 # default is #FFF
    moon_sun_background_color = "#515151"   # default is #515151

    # light mode
    text_color = "#222"             # default is #222
    content_bg_color = "#FAF9F6"    # default is #FAF9F6
    post_title_color = "#303030"    # default is #303030
    list_color = "#5a5a5a"          # default is #5a5a5a
    link_color = "#268bd2"          # default is #268bd2
    date_color = "#515151"          # default is #515151
    table_border_color = "#E5E5E5"  # default is #E5E5E5
    table_stripe_color = "#F9F9F9"  # default is #F9F9F9

    # dark mode
    text_color_dark = "#eee"            # default is #eee
    content_bg_color_dark = "#121212"   # default is #121212
    post_title_color_dark = "#DBE2E9"   # default is #DBE2E9
    list_color_dark = "#9d9d9d"         # default is #9d9d9d
    link_color_dark = "#268bd2"         # default is #268bd2
    date_color_dark = "#9a9a9a"         # default is #9a9a9a
    table_border_color_dark = "#515151" # default is #515151
    table_stripe_color_dark = "#202020" # default is #202020

    # Stuff i dont want for now
    # nope.avi
    # Plausible
    # plausible = true
    # plausible_domain = "poison.lukeorth.com"
    # plausible_script = "https://plausible.lukeorth.com/js/script.js"


[params.meta]
    favicon = true
[taxonomies]
    series = 'series'
    tags = 'tags'

