# comment out for now so we get relative links in the 
# html output, makes things easier
#baseURL: https://lichturm.de/
title: Lichturm
theme: poison
# the default is to just allow crawlers everywhere
# see https://gohugo.io/templates/robots/
enableRobotsTXT: true
pagination:
  pagersize: 10
pluralizelisttitles: false
defaultContentLanguage: de
# treat default language the same as others by having a dedicated subdir
defaultContentLanguageInSubdir: true
languages:
  de:
    contentDir: content/
    languageCode: de
    languageName: Deutsch
    weight: 1
    params:
      description: Welch schreckliche Nacht des Lesens mächtig zu sein!
      menu:
        - Name: Über  diese Seite
          URL: /de/about/
          HasChildren: false
        - Name: Alle Beiträge
          URL: /de/posts/
          #SubHeading: Neuerdings
          #HasChildren: true
          #Limit: 5
        - Name: Weitere Dienste
        #- Name: Wiki
        #  External: true
        #  URL: https://wiki.lichturm.de
        - Name: Foundry
          External: true
          URL: https://foundry.lichturm.de
  en:
    contentDir: content/
    languageCode: en-GB
    languageName: English
    weight: 10
    params:
      description: What a horrible night to be literate!
      menu:
        - Name: About this Page
          URL: /en/about/
          HasChildren: false
        - Name: All Posts
          URL: /en/posts/
          #SubHeading: Recent
          #HasChildren: true
          #Limit: 5
        - Name: Other Services
        #- Name: Wiki
        #  External: true
        #  URL: https://wiki.lichturm.de
        - Name: Foundry
          External: true
          URL: https://foundry.lichturm.de
 
params:
  # this determines what kind of page bundles are considered for the content
  # of the feed on the main page
  front_page_content:
    - posts
    - about
  brand: Lichturm
  brand_image: /images/lichturm.webp
  favicon: /images/lichturm_favicon.jpg
  dark_mode: true
  github_url: https://github.com/Atomsoldat
  #linkedin_url: https://linkedin.com
  email_url: mailto:lichturm@posteo.de
  #rss_icon: true
  #rss_section: posts
  meta:
    favicon: true
taxonomies:
  series: series
  tags: tags



  # BEGIN Default colours
  sidebar_bg_color: '#202020'
  sidebar_img_border_color: '#515151'
  sidebar_p_color: '#909090'
  sidebar_h1_color: '#FFF'
  sidebar_a_color: '#FFF'
  sidebar_socials_color: '#FFF'
  moon_sun_color: '#FFF'
  moon_sun_background_color: '#515151'
  button_label_color: '#FFF'
  button_background_color: '#515151'
  button_background_highlight_color: '#616161'
  text_color: '#222'
  content_bg_color: '#FAF9F6'
  post_title_color: '#303030'
  list_color: '#5a5a5a'
  link_color: '#268bd2'
  date_color: '#515151'
  table_border_color: '#E5E5E5'
  table_stripe_color: '#F9F9F9'
  text_color_dark: '#eee'
  content_bg_color_dark: '#121212'
  post_title_color_dark: '#DBE2E9'
  list_color_dark: '#9d9d9d'
  link_color_dark: '#268bd2'
  date_color_dark: '#9a9a9a'
  table_border_color_dark: '#515151'
  table_stripe_color_dark: '#202020'
  # END Default colours

