user  nginx;
worker_processes  auto;

# the Dockerfile for the nginx debian image links these to /dev/stdout, same with acces.log
# https://github.com/nginxinc/docker-nginx/blob/d21b4f2d90a1abb712a610678872e804267f4815/stable/debian/Dockerfile#L128
error_log  /var/log/nginx/error.log notice;

pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}


http {
#  server {
#    # redirect people accessing www subdomain
#    server_name www.lichturm.de;
#    return 301 $scheme://lichturm.de$request_uri;
#  }


  # main virtual server
  server {
    listen 80;
    listen  [::]:80;

    # .lichturm.de means *.lichturm.de + lichturm.de
    server_name  .lichturm.de;

    # 2nd parameter determines log format
    access_log  /var/log/nginx/access.log;

    location / {
      root   /usr/share/nginx/html;
      index  index.html index.htm;
    }

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

  }


  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';


  sendfile        on;
  #tcp_nopush     on;

  keepalive_timeout  65;

  #gzip  on;

  #include /etc/nginx/conf.d/*.conf;
}
